sudo: false

language: python

python:
  - 3.5

install:
  - pip install codecov

script:
  - set PYTHONPATH=%PYTHONPATH%; ./src/perceptron.py
  - coverage run ./test/perceptron.py

after_success:
  - codecov